apiVersion: apps/v1
kind: Deployment # Except this line
metadata:
  name: lms
spec:
  replicas: 1 # 1 pod should always run
  selector:
    matchLabels:
      app: lms
  template: # pod template
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: c1
        image: lms
        ports:
        - containerPort: 80