apiVersion: apps/v1
kind: Deployment 
metadata:
  name: lms
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: lms
  template: 
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: lms
        image: ravi2krishna/react-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lms-service
spec:
  type: LoadBalancer
  selector:
    app: lms
  ports:
    - protocol: TCP
      port: 80

